<div class="wrap">
	<h1>Список абитуриентов</h1>
		<form action="index.php" method="post">
			<label for="">Поиск:</label>
			<input type="text"  name="search">
			<input type="submit">
		</form>
		<table>
			<tr>
				<th><a href="index.php?order=name">Имя</a></th>
				<th><a href="index.php?order=sername">Фамилия</a></th>
				<th><a href="index.php?order=group">Номер группы</a></th>
				<th><a href="index.php?order=mark">Баллов</a></th>
			</tr>
			<?php foreach($students as $student):?>
			<tr>
				<td><?=htmlspecialchars($student['student_name']) ?></td>
				<td><?=htmlspecialchars($student['student_sername']) ?></td>
				<td><?=htmlspecialchars($student['student_group']) ?></td>
				<td><?=htmlspecialchars($student['student_mark']) ?></td>
			</tr>
		<?php endforeach ?>
		</table>
</div>